### ISSUE TITLE
Add developer examples in Wiki about ctools plugins, etc

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ctools#2]
I have a couple of modules on my "to port" or "in process of porting" list which use `ctools` as a dependency. It would help me greatly if the [Wiki](https://github.com/backdrop-contrib/ctools/wiki) contained an example of each basic ctools usage and the corresponding Backdrop equivalent. 

If someone can point me to an existing port that has already done some of this type of ctools to Backdrop conversion, I may be able to pull those examples into the Wiki myself.

e.g.
> Plugins -- tools to make it easy for modules to let other modules implement plugins from .inc files. Backdrop uses info hooks and callback functions (or callback classes) instead of plugins.

An example of a ctools plugin converted to Backdrop format would be most helpful.

**Comment by herbdool** [comment]
@laryn is it better in some ways to put it in the README or reference the wiki in the README? I can make a PR either way.

For reference, here is relevant info on what to do when converting a ctools plugin from Nate (from https://github.com/backdrop-ops/contrib/issues/104) which should help a lot in figuring out how to convert ctools plugins:

> So the primary parts of CTools that is not in core are "CTools plugins". The reason we did not include these in core is that they would have been a replacement for all *_info() hooks. And rather than having 2 ways of doing the same thing, we decided to stick with _info() hooks instead of converting them all to plugins. As we only moved a few things from CTools (e.g. Views "wizards" and the handlers from Panels and Page manager), it was much easier and more consistent with core to switch these to info hooks.
> 
> So in general, if you're porting a module that used CTools plugins, it's preferable to convert it to using info hooks instead.
> 
> Take for example our conversion of Views wizards into Backdrop. In Drupal 7, the existence of a wizard class was done via a file placed in a special directory (views_wizard). Here are the plugins for node and user:
> 
> https://api.drupal.org/api/views/plugins!views_wizard!node.inc/7
> https://api.drupal.org/api/views/plugins!views_wizard!users.inc/7
> 
> In Backdrop we instead made a hook, `hook_views_ui_wizards()` and included the same information that had been in the plugin in it. See `views_ui_views_ui_wizards()`.
> 
> Then when actually getting a list of wizards, both Backdrop and Drupal 7 have the same parent function `views_ui_get_wizards()`. The only difference is how we build the list:
> 
> Backdrop views_ui_get_wizards()
> 
>`$wizard_plugins = module_invoke_all('views_ui_wizards');`
>
> Drupal 7 views_ui_get_wizards()
> 
>   `ctools_include('plugins');
>   $wizard_plugins = ctools_get_plugins('views_ui', 'views_wizard');`
>
> So, in general you can avoid using a plugin by doing the following:
> 
> Move any `$plugin = array()` definitions from CTools plugin files into a new *_info() hook of your making.
> Find the place where previously your module called ctools_get_plugins() and change it instead to be `module_invoke_all('your_new_info')`.
> If necessary, include a 'file' value in the info hook to point at the plugin file. Then `module_load_include()` this file before calling its functions. In the case of Views wizards, that wasn't necessary because they are all classes and use the autoloader to load themselves.

**Comment by laryn** [comment]
@herbdool Yes, I think perhaps a reference in the README that links to more info in the Wiki would be appropriate? Thanks for following up here.

**Comment by herbdool** [comment]
@laryn review my PR?

**Comment by laryn** [comment]
@herbdool Wiki looks great. Thanks!

**Comment by herbdool** [comment]
@jenlampton can we merge the PR? https://github.com/backdrop-contrib/ctools/commit/df09c508e2dd39d0f40181e2ba0932da425ea24a

**Comment by herbdool** [comment]
@jenlampton silly me. I wasn't thinking and I had made the commit directly. Hope it's ok.
